services:
  nifi:
    image: apache/nifi:2.4.0
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443 # HTTPS is default in recent NiFi images
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current